services:
  my_app_web:  # Cambié el nombre del servicio aquí
    build:
      context: .  # Usa el Dockerfile en el directorio actual
    container_name: lily_dashboard
    restart: always
    ports:
      - "8012:7001"  # Redirige el puerto 7001 del contenedor al host
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_CA=${DB_SSL_CA}
      - SERVER_IP=0.0.0.0  # Exponer en todas las interfaces
    volumes:
      - ./logs:/app/logs  # Logs persistentes
      - ./app/config/AudiowebApp.pem:/app/config/AudiowebApp.pem  # Montar clave SSL en la carpeta config
    networks:
      - app-network
    env_file:
      - .env  # Cargar variables de entorno

networks:
  app-network:
    driver: bridge






